# Copyright (c) 2022-2024 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build example - Telink

on:
  push:
    branches:
      - feature/matter-telink-wall-lamp
  pull_request:
    branches-ignore:
            - 'dependabot/**'
  merge_group:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
  cancel-in-progress: true

env:
  CHIP_NO_LOG_TIMESTAMPS: true
  SOFTWARE_VERSION: 1.0.6

jobs:
  build:
    name: Telink
    env:
      BUILD_TYPE: telink

    runs-on: ubuntu-24.04
    if: github.actor != 'restyled-io[bot]'

    container:
      image: ghcr.io/project-chip/chip-build-telink:66
      volumes:
        - "/tmp/bloat_reports:/tmp/bloat_reports"
        - "/tmp/telink_build_artifacts:/tmp/telink_build_artifacts"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout submodules & Bootstrap
        uses: ./.github/actions/checkout-submodules-and-bootstrap
        with:
          platform: telink
          token: ${{ secrets.TELINK_SDK_PAT }}

      - name: Set up environment for size reports
        uses: ./.github/actions/setup-size-reports
        if: ${{ !env.ACT }}
        with:
          gh-context: ${{ toJson(github) }}

      - name: Update Zephyr to specific revision (for developers purpose)
        env:
          MATTER_TOKEN: ${{ secrets.TELINK_SDK_PAT }}
        run: |
          echo "Verifying GitHub access permissions using provided GitHub token..."
          curl -s -H "Authorization: token $MATTER_TOKEN" https://api.github.com/user
          echo "Running update_zephyr script in Matter build environment..."
          scripts/run_in_build_env.sh \
            "pip3 install requests &&  pip3 install pyyaml && python3 \
            scripts/tools/telink/update_zephyr.py \
            93c0de7914e7e93be4ef48592a665b6fb6ac44be \
            https://github.com/Leedarson-SmartLighting/matter-telink-luminaire-zephy \
            --token $MATTER_TOKEN"

      - name: Build example Telink (B92) Lighting App with OTA and 4Mb flash
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target 'telink-tlsr9528a-light-ota-4mb' build"
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
            telink tlsr9528a lighting-app-ota-4mb \
            out/telink-tlsr9528a-light-ota-4mb/zephyr/zephyr.elf \
            /tmp/bloat_reports/
          cp out/telink-tlsr9528a-light-ota-4mb/zephyr/zephyr.mcuboot.bin \
            /tmp/telink_build_artifacts/zephyr.mcuboot.bin
          cp out/telink-tlsr9528a-light-ota-4mb/zephyr/zephyr.bin \
            /tmp/telink_build_artifacts/telinkLightAppFW_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.bin
          cp out/telink-tlsr9528a-light-ota-4mb/zephyr/mcuboot_for_sign.bin \
            /tmp/telink_build_artifacts/telinkLightBtl_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.bin
          cp examples/lighting-app/telink/telinkLightCfg_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.json \
            /tmp/telink_build_artifacts/telinkLightCfg_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.json

      - name: clean out build output
        run: rm -rf ./out

      - name: Uploading Size Reports
        uses: ./.github/actions/upload-size-reports
        if: ${{ !env.ACT }}
        with:
          platform-name: Telink

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telink-examples
          path: |
            /tmp/telink_build_artifacts/*

  upload:
    name: Upload example
    needs: build
    runs-on: ubuntu-22.04
     
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: telink-examples
          path: /tmp/telink_build_artifacts
 
      - name: Debug file existence
        run: |
          ls -la "/tmp/telink_build_artifacts/"

      - name: Generate checksum
        id: checksha256
        run: |
          cd /tmp/telink_build_artifacts
          appfw_sha256=$(openssl sha256 -binary telinkLightAppFW_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.bin | base64)
          btl_sha256=$(openssl sha256 -binary telinkLightBtl_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.bin | base64)
          cfg_sha256=$(openssl sha256 -binary telinkLightCfg_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.json | base64)
          echo "appfw_sha256=$appfw_sha256" >> $GITHUB_OUTPUT
          echo "btl_sha256=$btl_sha256" >> $GITHUB_OUTPUT
          echo "cfg_sha256=$cfg_sha256" >> $GITHUB_OUTPUT

      - name: Upload ota file
        uses: inter-ikea/rs-hs-shipit-actions/upload-file@main
        id: otafile
        with:
          file_path: "/tmp/telink_build_artifacts/telinkLightAppFW_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.bin"
          api_key: ${{ secrets.SHIPIT_API_KEY }}
          api_url: ${{ vars.SHIPIT_URL }}
          friendlyName: "telinkLightAppFW_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.bin"
          version: "1"
          versionType: "INTEGER"
          checksum: ${{ steps.checksha256.outputs.appfw_sha256 }}
          checksumAlgorithm: "SHA256"
          labels: "otafile" # important

      - name: Upload bootloader file
        uses: inter-ikea/rs-hs-shipit-actions/upload-file@main
        id: btlfile
        with:
          file_path: "/tmp/telink_build_artifacts/telinkLightBtl_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.bin"
          api_key: ${{ secrets.SHIPIT_API_KEY }}
          api_url: ${{ vars.SHIPIT_URL }}
          friendlyName: "telinkLightBtl_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.bin"
          version: "1"
          versionType: "INTEGER"
          checksum: ${{ steps.checksha256.outputs.btl_sha256 }}
          checksumAlgorithm: "SHA256"
          labels: "btlfile" # important

      - name: Upload config file
        uses: inter-ikea/rs-hs-shipit-actions/upload-file@main
        id: cfgfile
        with:
          file_path: "/tmp/telink_build_artifacts/telinkLightCfg_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.json"
          api_key: ${{ secrets.SHIPIT_API_KEY }}
          api_url: ${{ vars.SHIPIT_URL }}
          friendlyName: "telinkLightCfg_${{ github.run_number }}_0x117C_0x9000_${{ env.SOFTWARE_VERSION }}.json"
          version: "1"
          versionType: "INTEGER"
          checksum: ${{ steps.checksha256.outputs.cfg_sha256 }}
          checksumAlgorithm: "SHA256"
          labels: "cfgfile" # important

#      - name: Start Telink signing
#        uses: inter-ikea/rs-hs-shipit-actions/start-matter-telink-signing@main
#        id: start-matter-telink-signing
#        with:
#          api_key: ${{ secrets.SHIPIT_API_KEY }}
#          api_url: ${{ vars.SHIPIT_URL }}
#          ota_file: ${{ steps.otafile.outputs.id }}
#          btl_file: ${{ steps.btlfile.outputs.id }}
#          cfg_file: ${{ steps.cfgfile.outputs.id }}
#          key_variant: "PROD"